# Site settings
title: Linux Accessibility 
description: > # this means to ignore newlines until "baseurl:"
  A 2015 inventory of the tools and technologies for using Linux if its default
  assumptions about your vision or physical abilities are wrong. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://linux-accessibility.github.io" # the base hostname & protocol for your site
github_username: linux-accessibility 
permalink: pretty

# Build settings
markdown: kramdown
